### ISSUE TITLE
Lags on low end PCs

### ISSUE THREAD

**Issue by Kant8** [dota2unofficial/overthrow2#104]
As you may know since like the beginning of november people with potatoes instead of PC cannot play because of major fps drop which is defenetely CPU based. Even if fps is high enough, you see that everyting lags like you have sleep(100) every second line of code.
I've downloaded code, launched my copy, removed all cou cores from dota2.exe instead of only one to reduce fps, and started searching what causes lags. 

I've eventually found, that in file `content\panorama\layout\custom_game\common\cosmetic_abilities\creator.js` in the end you call `setInterval` with interval 0, which is defenetely not intended. I changed it to 1000, saved file, alt-tabbed into game and hooray, I got 55-70 fps instead of barely 25.
Then I realized, that it's not possible, because this file is ancient enough. I restarted game and again got 25 fps.
Now every time I edit anyting while game is running in *.js files under content\panorama folders, even adding a semicolon, engine rebuild smth and your fps doubles.

I have no idea how this works, but I've seen commits with descriptions like "compiled maps". Mb smth is compiled wrong, or got outdated, and dota does some shit inside because of it?

Hope you'll find solution, me and my friends want to play again :)

**Comment by darklordabc** [comment]
Can u test it now again and see if it has been fixed? If so, by how much? Is it back to normal?

**Comment by Kant8** [comment]
Don't see any commits here so can test only from regular game, not from workshop tools. But at least it works on 60 fps now with single core. Poor performance is only during like first 10-15 seconds after heroes spawned, but thats ok.

But still see some minor spikes every few seconds, looks like it's synced with particles error in console `Failed to find attachment point specified for particle effect anim event. Trying to spawn effect 'particles/overboss_chalice_fizz.vpcf' on attachment named 'bubbles' on model models/props_structures/midas_throne/kobold_underboss.vmdl` and `
Failed to find attachment point specified for particle effect anim event. Trying to spawn effect 'particles/overboss_chalice_splash.vpcf' on attachment named 'splash' on model models/props_structures/midas_throne/kobold_underboss.vmdl`

I'll ask my friend who suffered from problem to test it too.

**Comment by Kant8** [comment]
Yes, he reports it's ok now. Thank you.

Hop you will fix that particles too soon.
