### ISSUE TITLE
Doom's Devour Auras do not apply to allies

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/overthrow2#69]
The auras he obtains from the extra abilities he recieves from his Devour ability, do not apply to allies, they should.

**Comment by Gichik** [comment]
Each neutral aura has an additional “bonus” modifier for this aura.

For example, satyr_hellcaller_unholy_aura:
modifier_satyr_hellcaller_unholy_aura (work in this situation)
modifier_satyr_hellcaller_unholy_aura_bonus (not work in this situation)

I don’t know why, but it will not be activated if the skill itself was added through the lua. If the skill is pre-registered in the hero (datadriven), then when it is level up, the bonus is activated.

**Comment by Gichik** [comment]
I suggest you just implement your own neutral auras.

**Comment by darklordabc** [comment]
Can you recreate the passive auras?

**Comment by Gichik** [comment]
Auras - yes.
Active skills - in their true form is problematic for me (take a long time).

**Comment by darklordabc** [comment]
I think the skills and passives work, it's the only auras that are not working as far as i know

**Comment by Gichik** [comment]
1) Added "devour_taskmaster_speed_aura.lua" in "game/scripts/vscripts/abilities/heroes/".
(https://github.com/dota2unofficial/overthrow2/tree/master/game/scripts/vscripts/abilities/heroes)

2) Change "kobold_taskmaster_speed_aura" on "devour_taskmaster_speed_aura" in your "doom_bringer_devour.lua".
(https://github.com/dota2unofficial/overthrow2/blob/master/game/scripts/vscripts/abilities/heroes/doom_bringer_devour.lua)

3) From "settings.txt" copy first block (npc_abilities_custom) to your "game/scripts/npc/npc_abilities_custom.txt".
(https://github.com/dota2unofficial/overthrow2/blob/master/game/scripts/npc/npc_abilities_custom.txt)

4) From  copy second block (addon_english) to your "game/resource/addon_english.txt".
(https://github.com/dota2unofficial/overthrow2/blob/master/game/resource/addon_english.txt)


[devour.zip](https://github.com/dota2unofficial/overthrow2/files/3665258/devour.zip)

**Comment by darklordabc** [comment]
Fixed
