### ISSUE TITLE
Unconfirmed: Streaks no longer working

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/overthrow2#71]
![image](https://user-images.githubusercontent.com/16277198/50845661-50d0da00-1365-11e9-8e24-5e74bd22253a.png)
https://steamcommunity.com/workshop/filedetails/discussion/1517661692/1744480967016151119/

**Comment by darklordabc** [comment]
Can any one confirm?

**Comment by ark120202** [comment]
That probably was https://github.com/dota2unofficial/server/commit/c1101402541ba8d2cb124227b3e85e70813a8449
