### ISSUE TITLE
Add Chinese and Korean announcer files 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/overthrow2#93]
Original Chat Wheel Plan: https://www.diffchecker.com/dstmKRMo

Its missing the Chinese and Korean announcers, here they are below. 

-Chinese Announcer-
1.啊，队友呢？队友呢？队友呢？！队友呢？！？！
2.玩不了啦!
3.破两路更好打, 是吧?
4.天火!
5.加油!
6.走好, 不送
7.这波不亏

-Chinese Announcer 2-
8.葫芦娃救爷爷
9.你气不气?
10.这就是高富帅啊
11.干嘛呢兄弟
12.拜托谁去杀了他吧
13.漂~ 亮！
14.脸都秀歪啦
15.再见了宝贝儿！

Korean
16.네, 노, 네, 노 노 노!
17.스캔 돌려야 되요 따라란따란따라라라란 스캔 돌려야 된다고요!
18.Mommy! I got me! Immortality!
19.Roshan! Roshan! Roshan!
20.골드 부활 못 해! YOLO! 골드 부활 못 해! YOLO!
21.10억짜리 꿈의 고리! 15억짜리 꿈의 고리!

I've attached the audio files in this google folder: https://drive.google.com/drive/folders/1Wo38yTQYYr12iLWYpH2L6VL8t5Y6YuRk?usp=sharing

**Comment by darklordabc** [comment]
@Niker323 is this nearly done?

**Comment by Niker323** [comment]
It's all done
